// 🔮 Significados Tarot El Valle
// Estilo mediterráneo: naturaleza, paisajes, elementos del Valle del Rock
// Sin mencionar nombre de carta en los significados

const SIGNIFICADOS_VALLE = {
  // ═══════════════ ARCANOS MAYORES ═══════════════
  "00": { upright: "Caminante libre, espíritu indómito, conexión con la tierra.", reversed: "Desorientación, pérdida de rumbo, peligro en el camino." },
  "01": { upright: "Habilidad manual, creación con las manos, oficio sagrado.", reversed: "Engaño, habilidad mal usada, falsedad." },
  "02": { upright: "Conocimiento ancestral, sabiduría de la tierra, intuición.", reversed: "Secretos ocultos, conocimiento inaccesible." },
  "03": { upright: "Fertilidad, abundancia natural, crecimiento orgánico, nutrición.", reversed: "Dependencia, estancamiento, falta de crecimiento." },
  "04": { upright: "Autoridad natural, estructura comunitaria, orden establecido.", reversed: "Tiranía, rigidez, abuso de autoridad." },
  "05": { upright: "Enseñanza oral, tradición, guía espiritual, sabiduría.", reversed: "Rebelión, herejía, cuestionar tradiciones." },
  "06": { upright: "Elección moral, dualidad, tentación. Decidir entre direcciones.", reversed: "Indecisión, mala elección, tentación." },
  "07": { upright: "Victoria, avance, dominio del camino. Conquistar territorio.", reversed: "Derrota, falta de control, estancamiento." },
  "08": { upright: "Equilibrio, verdad, justicia natural. Consecuencias justas.", reversed: "Injusticia, deshonestidad, desequilibrio." },
  "09": { upright: "Búsqueda interior, soledad reflexiva, camino espiritual.", reversed: "Aislamiento, evasión, soledad no deseada." },
  "10": { upright: "Ciclos naturales, cambio, destino. Lo que gira, regresa.", reversed: "Resistencia al cambio, estancamiento." },
  "11": { upright: "Coraje, dominio animal, fuerza interior pura.", reversed: "Debilidad, cobardía, falta de control." },
  "12": { upright: "Pausa, nueva perspectiva, renuncia. Ver al revés.", reversed: "Estancamiento, sacrificio innecesario." },
  "13": { upright: "Transformación, fin de ciclo, renacimiento. Muerte y renacimiento natural.", reversed: "Resistencia al cambio, aferrarse." },
  "14": { upright: "Moderación, armonía, mezcla de opuestos. Paciencia.", reversed: "Desequilibrio, excesos, impaciencia." },
  "15": { upright: "Dependencia, ataduras, materialismo. Cadenas autoimpuestas.", reversed: "Liberación, ruptura, libertad." },
  "16": { upright: "Destrucción súbita, revelación, cambio violento. Derrumbe.", reversed: "Evitar desastre, resistencia al cambio." },
  "17": { upright: "Esperanza, inspiración, renovación. Agua que fluye, vida.", reversed: "Desesperanza, sequedad espiritual." },
  "18": { upright: "Ilusión, miedo, subconsciente. Lo oculto se manifiesta.", reversed: "Superar miedos, claridad." },
  "19": { upright: "Éxito, vitalidad, alegría. Luz del sol, energía positiva.", reversed: "Tristeza, nublar, falta de luz." },
  "20": { upright: "Renacimiento, llamado, segunda oportunidad. Despertar.", reversed: "Negación, autocrítica, estancamiento." },
  "21": { upright: "Completitud, logro, fin de viaje. Integración total.", reversed: "Incompletitud, falta de cierre." },

  // ═══════════════ COPAS ═══════════════
  "22": { upright: "Nueva fuente emocional, río que nace, potencial puro.", reversed: "Cierre, represión, sequedad." },
  "23": { upright: "Unión de ríos, equilibrio, armonía entre dos almas.", reversed: "Desarmonía, conflicto, separación." },
  "24": { upright: "Celebración comunitaria, alegría, río ancho, expansión.", reversed: "Excesos, soledad, traición." },
  "25": { upright: "Estancamiento, contemplación, rechazo, pausa reflexiva.", reversed: "Acción, movimiento, nuevas aguas." },
  "26": { upright: "Pérdida, decepción, caída, dificultad emocional.", reversed: "Aceptación, superación, flujo." },
  "27": { upright: "Nostalgia, recuerdo, corriente pasada, evocación.", reversed: "Vivir en el pasado, estancamiento." },
  "28": { upright: "Fantasía, ilusión, opciones confusas, sueños.", reversed: "Claridad, decisión, aguas claras." },
  "29": { upright: "Abandono, buscar el mar, dejar atrás, transición.", reversed: "Apego, miedo al cambio." },
  "30": { upright: "Satisfacción, fuente, bienestar, gratitud, plenitud.", reversed: "Insatisfacción, codicia, sequedad." },
  "31": { upright: "Plenitud, armonía familiar, río que llega al mar.", reversed: "Conflicto, desilusión, sequedad." },
  "32": { upright: "Noticia pequeña, inspiración fresca, mensaje suave.", reversed: "Inmadurez, noticias malas." },
  "33": { upright: "Romance, movimiento emocional, poesía, arte.", reversed: "Celos, manipulación." },
  "34": { upright: "Mujer intuitiva, empática, sanadora, ola serena.", reversed: "Dependencia, inseguridad." },
  "35": { upright: "Hombre sabio, emocionalmente estable, profundo como el río.", reversed: "Manipulación, agresión." },

  // ═══════════════ ESPADAS ═══════════════
  "36": { upright: "Nuevo pensamiento, claridad, verdad fresca, brisa.", reversed: "Confusión, malentendidos, calma." },
  "37": { upright: "Indecisión, equilibrio, viento en calma, pausa.", reversed: "Decisión, acción, viento fresco." },
  "38": { upright: "Dolor, tristeza, betrayl, tormenta interior.", reversed: "Perdón, recuperación, sol." },
  "39": { upright: "Descanso, meditación, calma, brisa suave.", reversed: "Agitación, ansiedad, viento fuerte." },
  "40": { upright: "Conflicto, rivalidad, viento fuerte, desacuerdo.", reversed: "Acuerdo, reconciliación, calma." },
  "41": { upright: "Transición, cambio, viento favorable, avance.", reversed: "Estancamiento, resistencia, calma." },
  "42": { upright: "Estrategia, astucia, viento silencioso, secretos.", reversed: "Confesión, honestidad, viento claro." },
  "43": { upright: "Restricción, ataduras, viento atrapado, prisión.", reversed: "Liberación, empowerment, viento libre." },
  "44": { upright: "Ansiedad, preocupación, viento nocturno, pesadilla.", reversed: "Esperanza, alivio, viento nuevo." },
  "45": { upright: "Final, destrucción, huracán, pero nuevo amanecer.", reversed: "Recuperación, resistencia, calma." },
  "46": { upright: "Observar, planificar, viento suave, susurro.", reversed: "Espionaje, críticas, viento malicioso." },
  "47": { upright: "Acción rápida, determinación, ráfaga, viento fuerte.", reversed: "Impulsividad, agresión, viento destructivo." },
  "48": { upright: "Mujer directa, observadora, justa, huracán sereno.", reversed: "Crueldad, fríaldad, viento helado." },
  "49": { upright: "Autoridad intelectual, justicia, tormenta justa.", reversed: "Tiranía, abuso, viento destructivo." },

  // ═══════════════ BASTOS ═══════════════
  "50": { upright: "Inspiración pura, llama nueva, potencia, chispa.", reversed: "Falta de dirección, cenizas, pérdida de fuego." },
  "51": { upright: "Planificación, visión, dirección del fuego, llama.", reversed: "Miedo al cambio, estancamiento, frialdad." },
  "52": { upright: "Expansión, visión amplia, hoguera, fuego grande.", reversed: "Frustración, retrasos, frialdad." },
  "53": { upright: "Estabilidad, celebración, lumbre del hogar, fuego cálido.", reversed: "Transición, inestabilidad, apagón." },
  "54": { upright: "Conflicto, rivalidad, incendio, fuego intenso.", reversed: "Acuerdo, armonía, calma." },
  "55": { upright: "Éxito reconocido, victoria, fuego triunfante.", reversed: "Derrota, arrogancia, cenizas." },
  "56": { upright: "Perseverar, mantener la llama, resistencia, fuego constante.", reversed: "Rendirse, agotamiento, apagón." },
  "57": { upright: "Movimiento rápido, velocidad, fuego veloz, avance.", reversed: "Retrasos, estancamiento, frialdad." },
  "58": { upright: "Aguante, fortaleza, llama constante, persistencia.", reversed: "Agotamiento, paranoia, cenizas." },
  "59": { upright: "Responsabilidad, sobrecarga, hoguera pesada, carga.", reversed: "Liberación, alivio, fuego ligero." },
  "60": { upright: "Entusiasmo, exploración, aventura, llama joven.", reversed: "Inmadurez, falta de dirección, frialdad." },
  "61": { upright: "Pasión, energía, aventura, llamas, fuego puro.", reversed: "Impulsividad, arrogancia, incendio." },
  "62": { upright: "Confianza, carisma, determinación, fuego cálido.", reversed: "Celos, egoísmo, frialdad." },
  "63": { upright: "Liderazgo, visión, emprendimiento, fuego poderoso.", reversed: "Tiranía, impulsividad, destrucción." },

  // ═══════════════ OROS ═══════════════
  "64": { upright: "Nueva oportunidad, prosperidad, semilla fértil, inicio.", reversed: "Oportunidad perdida, tierra estéril." },
  "65": { upright: "Equilibrio, adaptabilidad, gestión del suelo, tierra.", reversed: "Desequilibrio, mala gestión, erosión." },
  "66": { upright: "Trabajo en equipo, maestría, cosecha, cultivo.", reversed: "Mediocridad, desacuerdo, tierra pobre." },
  "67": { upright: "Control, seguridad, ahorro, granero, almacenar.", reversed: "Avaricia, generosidad excesiva, despilfarro." },
  "68": { upright: "Dificultad, pobreza, tierra seca, sequía.", reversed: "Recuperación, ayuda, lluvia." },
  "69": { upright: "Generosidad, dar y recibir, trueque, equilibrio.", reversed: "Deudas, dependencia, generosidad falsa." },
  "70": { upright: "Paciencia, inversión, espera, cosecha, frutos.", reversed: "Falta de paciencia, malgasto, cosecha pobre." },
  "71": { upright: "Habilidad técnica, dedicación, artesanía, oficio.", reversed: "Mediocridad, aburrimiento, falta de pasión." },
  "72": { upright: "Independencia, lujo, abundancia, tierra fértil.", reversed: "Dependencia, excesos, tierra agotada." },
  "73": { upright: "Familia, estabilidad, herencia, legado, tierra propia.", reversed: "Pérdida, problemas familiares, tierra perdida." },
  "74": { upright: "Estudio, ambición, oportunidad, semilla nueva.", reversed: "Falta de progreso, pereza, tierra ociosa." },
  "75": { upright: "Diligencia, rutina, perseverancia, arado, trabajo constante.", reversed: "Pereza, estancamiento, tierra sin trabajar." },
  "76": { upright: "Nutrición, generosidad, tierra fértil, abundancia natural.", reversed: "Dependencia, descuido, tierra descuidada." },
  "77": { upright: "Éxito financiero, liderazgo práctico, terruño, abundancia.", reversed: "Avaricia, materialismo, tierra codiciada." }
};
