// 🔮 Significados Tarot de Thoth
// Estilo oculto: Aleister Crowley, símbolos alquímicos y astronómicos
// Sin mencionar nombre de carta en los significados

const SIGNIFICADOS_THOTH = {
  // ═══════════════ ARCANOS MAYORES ═══════════════
  "00": { upright: "Energía caótica pura, potencial ilimitado, locura divina, Dionisos.", reversed: "Caos destructivo, disipación de energía, locura real." },
  "01": { upright: "Habilidad mental, comunicación, manifestación through will. El arte de crear.", reversed: "Engaño, habilidad mal dirigida, charlatanería." },
  "02": { upright: "Misterio, silencio, conocimiento oculto, fertilidad latente. Isis.", reversed: "Secretos revelados prematuramente, confusión." },
  "03": { upright: "Fertilidad, amor, belleza, abundancia natural. Venus.", reversed: "Infertilidad, dependencia, exceso de lujo." },
  "04": { upright: "Voluntad, liderazgo, energía dirigida, dominio. Aries.", reversed: "Tiranía, debilidad, falta de voluntad." },
  "05": { upright: "Enseñanza, expansión espiritual, guía sagrada. Júpiter.", reversed: "Dogma, rebelión, exceso de autoridad." },
  "06": { upright: "Unión de opuestos, elección, polaridad. Géminis.", reversed: "Conflicto, indecisión, disolución." },
  "07": { upright: "Victoria, avance, dominio emocional. Cáncer.", reversed: "Derrota, pérdida de control, agresión." },
  "08": { upright: "Equilibrio, verdad, armonía, ley cósmica. Libra.", reversed: "Injusticia, desequilibrio, corrupción." },
  "09": { upright: "Búsqueda interior, discernimiento, trabajo solitario. Virgo.", reversed: "Aislamiento, paranoia, evasión." },
  "10": { upright: "Ciclos cósmicos, destino, rotación universal. Júpiter-Saturno.", reversed: "Estancamiento, resistencia al destino." },
  "11": { upright: "Coraje, dominio animal, fuerza interior bruta. León.", reversed: "Debilidad, cobardía, falta de control." },
  "12": { upright: "Sacrificio, visión, trascendencia, disolución del ego. Neptuno.", reversed: "Estancamiento, martydom innecesario." },
  "13": { upright: "Transformación radical, fin y renacimiento, transmutación. Escorpio.", reversed: "Resistencia al cambio, estancamiento." },
  "14": { upright: "Equilibrio, moderación, armonía de opuestos. Sagitario.", reversed: "Desequilibrio, excesos, impaciencia." },
  "15": { upright: "Limitación, estructura, ambición terrenal. Capricornio.", reversed: "Liberación, ruptura de límites." },
  "16": { upright: "Destrucción, fuerza bruta, cambio súbito y violento. Marte.", reversed: "Evitar destrucción, resistencia al cambio." },
  "17": { upright: "Esperanza, inspiración, energía cósmica. Acuario.", reversed: "Desesperanza, desconexión." },
  "18": { upright: "Ilusión, subconsciente, lo oculto, sueños. Piscis.", reversed: "Superar ilusiones, verdad revelada." },
  "19": { upright: "Éxito, vitalidad, energía radiante, plenitud. Sol.", reversed: "Tristeza, oscuridad, falta de energía." },
  "20": { upright: "Renacimiento, transformación profunda, despertar. Plutón.", reversed: "Negación, autocrítica, estancamiento." },
  "21": { upright: "Completitud, integración, fin de ciclo cósmico. Saturno.", reversed: "Incompletitud, falta de cierre." },

  // ═══════════════ COPAS ═══════════════
  "22": { upright: "Origen emocional, potencial puro, apertura del corazón.", reversed: "Cierre emocional, represión." },
  "23": { upright: "Equilibrio emocional, polaridad, armonía entre dos almas.", reversed: "Desarmonía, conflicto emocional." },
  "24": { upright: "Expansión emocional, alegría, celebración, comunidad.", reversed: "Excesos, soledad emocional." },
  "25": { upright: "Estancamiento emocional, contemplación, rechazo a nuevas ofertas.", reversed: "Acción emocional, motivación." },
  "26": { upright: "Pérdida emocional, decepción, dificultad para soltar.", reversed: "Aceptación, superación." },
  "27": { upright: "Nostalgia, recuerdo, inocencia, conexión con el pasado.", reversed: "Vivir en el pasado, inmadurez." },
  "28": { upright: "Fantasía, ilusión, opciones tentadoras, sueños.", reversed: "Claridad, decisión real." },
  "29": { upright: "Abandono, búsqueda, dejarse ir, transición.", reversed: "Apego, miedo al cambio." },
  "30": { upright: "Satisfacción, logro emocional, deseos cumplidos.", reversed: "Insatisfacción, codicia." },
  "31": { upright: "Plenitud emocional, felicidad total, armonía familiar.", reversed: "Conflicto, desilusión." },
  "32": { upright: "Noticia emocional, inspiración joven, mensaje inesperado.", reversed: "Inmadurez, noticias malas." },
  "33": { upright: "Romance, offering, poesía, arte emocional.", reversed: "Celos, manipulación." },
  "34": { upright: "Intuición, empatía, sanación, maestría emocional.", reversed: "Dependencia, inseguridad." },
  "35": { upright: "Sabiduría emocional, diplomacia, estabilidad.", reversed: "Manipulación, agresión." },

  // ═══════════════ ESPADAS ═══════════════
  "36": { upright: "Verdad, claridad, breakthrough mental, filo de la mente.", reversed: "Confusión, engaño." },
  "37": { upright: "Indecisión, bloqueo, equilibrio precario entre dos opciones.", reversed: "Decisión, claridad." },
  "38": { upright: "Dolor, tristeza, betrayl intelectual, tres caminos.", reversed: "Perdón, recuperación." },
  "39": { upright: "Descanso, meditación, pausa reflexiva, quietud.", reversed: "Agitación, ansiedad." },
  "40": { upright: "Rivalidad, desacuerdo, victoria pírrica, conflicto.", reversed: "Acuerdo, reconciliación." },
  "41": { upright: "Transición, cambio, avance, río fluyendo.", reversed: "Estancamiento, resistencia." },
  "42": { upright: "Astucia, secretos, acción solitaria, estrategia oculta.", reversed: "Confesión, honestidad." },
  "43": { upright: "Ataduras mentales, victimismo, prisión mental.", reversed: "Liberación, empowerment." },
  "44": { upright: "Preocupación, pesadillas, culpa, ansiedad nocturna.", reversed: "Esperanza, alivio." },
  "45": { upright: "Final, rock bottom, nuevo amanecer después de la oscuridad.", reversed: "Recuperación, resistencia." },
  "46": { upright: "Curiosidad, vigilancia, plan, observar antes de actuar.", reversed: "Espionaje, críticas." },
  "47": { upright: "Acción rápida, determinación, avance veloz.", reversed: "Impulsividad, agresión." },
  "48": { upright: "Independencia, claridad, justicia, directriz.", reversed: "Crueldad, fríaldad." },
  "49": { upright: "Liderazgo intelectual, estrategia, autoridad mental.", reversed: "Tiranía, abuso." },

  // ═══════════════ BASTOS ═══════════════
  "50": { upright: "Inspiración pura, fuego creativo, potencia, chispa.", reversed: "Falta de dirección, pérdida de fuego." },
  "51": { upright: "Planificación, visión, dirección, polaridad de acción.", reversed: "Miedo al cambio, estancamiento." },
  "52": { upright: "Visión amplia, exploración, crecimiento, expansión.", reversed: "Frustración, retrasos." },
  "53": { upright: "Celebración, logro estable, hogar, estabilidad creativa.", reversed: "Transición, inestabilidad." },
  "54": { upright: "Rivalidad, desafío, competencia, conflicto creativo.", reversed: "Acuerdo, armonía." },
  "55": { upright: "Éxito reconocido, logro público, victoria creativa.", reversed: "Derrota, arrogancia." },
  "56": { upright: "Perseverar, mantener posiciones, defensa creativa.", reversed: "Rendirse, agotamiento." },
  "57": { upright: "Movimiento rápido, avance, noticias, velocidad.", reversed: "Retrasos, estancamiento." },
  "58": { upright: "Persistencia, fortaleza, aguante, resistencia.", reversed: "Agotamiento, paranoia." },
  "59": { upright: "Responsabilidad, sobrecarga, deber, carga.", reversed: "Liberación, alivio." },
  "60": { upright: "Entusiasmo, exploración, aventura, mensajero joven.", reversed: "Inmadurez, falta de dirección." },
  "61": { upright: "Pasión, energía, aventura, acción audaz.", reversed: "Impulsividad, arrogancia." },
  "62": { upright: "Confianza, carisma, determinación, maestría.", reversed: "Celos, egoísmo." },
  "63": { upright: "Liderazgo, visión, emprendimiento, autoridad creativa.", reversed: "Tiranía, impulsividad." },

  // ═══════════════ OROS ═══════════════
  "64": { upright: "Nueva oportunidad, prosperidad, inicio, semilla material.", reversed: "Oportunidad perdida, falta de plan." },
  "65": { upright: "Gestión, adaptabilidad, flexibilidad, equilibrio práctico.", reversed: "Desequilibrio, mala gestión." },
  "66": { upright: "Trabajo en equipo, maestría, colaboración, creación.", reversed: "Mediocridad, desacuerdo." },
  "67": { upright: "Seguridad, ahorro, protección, control material.", reversed: "Avaricia, generosidad excesiva." },
  "68": { upright: "Dificultad, pobreza, aislamiento, necesidad.", reversed: "Recuperación, ayuda." },
  "69": { upright: "Dar y recibir, equilibrio, generosidad material.", reversed: "Deudas, dependencia." },
  "70": { upright: "Paciencia, inversión, espera, evaluación.", reversed: "Falta de paciencia, malgasto." },
  "71": { upright: "Habilidad técnica, dedicación, maestría práctica.", reversed: "Mediocridad, aburrimiento." },
  "72": { upright: "Lujo, autosuficiencia, logro, independencia.", reversed: "Dependencia, excesos." },
  "73": { upright: "Familia, estabilidad, tradición, legado.", reversed: "Pérdida, problemas familiares." },
  "74": { upright: "Estudio, ambición, práctica, oportunidad material.", reversed: "Falta de progreso, pereza." },
  "75": { upright: "Diligencia, rutina, perseverancia, trabajo constante.", reversed: "Pereza, estancamiento." },
  "76": { upright: "Nutrición, generosidad, práctica, abundancia.", reversed: "Dependencia, descuido." },
  "77": { upright: "Éxito financiero, liderazgo práctico, logro material.", reversed: "Avaricia, materialismo." }
};
