// 🔮 Significados Rider-Waite-Smith
// Estilo narrativo: escenas con personas, paisajes, historias
// Basado en la tradición de Arthur Edward Waite (1909)
// Sin mencionar nombre de carta en los significados

const SIGNIFICADOS_RIDER = {
  // ═══════════════ ARCANOS MAYORES ═══════════════
  "00": { upright: "Nuevos comienzos, espontaneidad, libertad. Un joven camina despreocupado hacia el borde de un acantilado, confiando en el universo. Principios llenos de posibilidades.", reversed: "Imprudencia, riesgo innecesario, falta de dirección. Actuar sin pensar en las consecuencias, caer en la trampa de la ingenuidad." },
  "01": { upright: "Habilidad, manifestación, concentración. Las herramientas de los cuatro elementos sobre la mesa. Tienes todo lo que necesitas para crear tu realidad.", reversed: "Manipulación, engaño, falta de habilidad. Usar el talento para fines incorrectos, potencial desaprovechado." },
  "02": { upright: "Intuición, misterio, conocimiento oculto. Sentada entre las columnas B y J, guardando secretos detrás del velo. Escuchar tu voz interior.", reversed: "Secretos revelados, confusión, falta de intuición. Ignorar las señales internas, superficiales." },
  "03": { upright: "Abundancia, fertilidad, naturaleza. Rodeada de jardines luxuriantes, corona de estrellas, símbolo de Venus. Creatividad y provisioning maternal.", reversed: "Dependencia, carencia, bloqueo creativo. Falta de atención al cuerpo o la naturaleza, esterilidad emocional." },
  "04": { upright: "Autoridad, estructura, liderazgo. Sentado en el trono de piedra con cabezas de carnero. Disciplina, estabilidad, protección firme.", reversed: "Tiranía, rigidez, abuso de poder. Falta de autoridad o exceso de control opresivo." },
  "05": { upright: "Tradición, espiritualidad, enseñanza. Bendice a sus dos acólitos. Buscar guía espiritual, seguir un camino establecido.", reversed: "Rebelión, unconventional, romper tradiciones. Cuestionar las normas establecidas, buscar tu propia verdad." },
  "06": { upright: "Amor, armonía, elección. Ante el ángel Raphael, árboles del conocimiento y la vida. Relaciones significativas, alineación de valores.", reversed: "Desequilibrio, conflicto, mala elección. Duda en una relación importante, desalineación de valores." },
  "07": { upright: "Victoria, determinación, voluntad. Tirado por esfinges negra y blanca. Superar obstáculos, avanzar con fuerza y control.", reversed: "Falta de control, agresión, derrota. Perder el rumbo por exceso de fuerza o dirección." },
  "08": { upright: "Valor, persuasión, fuerza interior. Doma al león con suavidad, infinito sobre la cabeza. Paciencia, compasión, dominio propio.", reversed: "Debilidad, inseguridad, falta de autocontrol. Miedo a enfrentar situaciones difíciles." },
  "09": { upright: "Introspección, soledad, guía interior. En la cima de la montaña con la linterna. Buscar respuestas dentro de ti, retiro espiritual.", reversed: "Aislamiento, soledad no deseada, negatividad. Evitar la compañía o el consejo necesario." },
  "10": { upright: "Cambio, ciclo, destino. La Rueda gira con símbolos hebreos y alquímicos. Los tiempos cambian, buenos momentos por venir.", reversed: "Mala racha, resistencia al cambio, mala suerte. Período difícil que eventualmente pasará." },
  "11": { upright: "Equidad, verdad, ley. Con la espada y balanza. Consecuencias justas, honestidad, objetividad.", reversed: "Injusticia, deshonestidad, sesgo. Falta de equidad o consecuencias injustas." },
  "12": { upright: "Sacrificio, espera, nueva perspectiva. Boca abajo del árbol vivo. Soltar, ver las cosas desde otro ángulo, iluminación.", reversed: "Estancamiento, indecisión, sacrificio innecesario. Resistencia a cambiar de perspectiva." },
  "13": { upright: "Transformación, final, renacimiento. En armadura negra sobre caballo blanco. Fin de un ciclo, liberación, cambio profundo.", reversed: "Resistencia al cambio, estancamiento, miedo. Aferrarse a lo que ya no funciona." },
  "14": { upright: "Equilibrio, moderación, paciencia. Vierte agua entre dos copas. Armonía, curación, síntesis de opuestos.", reversed: "Desequilibrio, excesos, impaciencia. Falta de armonía en la vida, exceso en algo." },
  "15": { upright: "Dependencia, materialismo, sombras. Sobre el pedestal, cadenas flojas. Apego, tentación, cadenas autoimpuestas.", reversed: "Liberación, ruptura de cadenas, despertar. Soltar dependencias, encontrar libertad." },
  "16": { upright: "Destrucción, revelación, cambio súbito. Golpeada por rayos. Derrumbe de estructuras falsas, verdad repentina.", reversed: "Evitar el desastre, resistencia al cambio, miedo. Postergar lo inevitable." },
  "17": { upright: "Esperanza, inspiración, serenidad. Vierte agua bajo un cielo estrellado. Fe en el futuro, sanación, renovación.", reversed: "Desesperanza, falta de fe, desilusión. Perder la conexión con lo espiritual." },
  "18": { upright: "Ilusión, miedo, subconsciente. Con sus dos torres y caminos. Sueños, intuición, lo oculto se revela.", reversed: "Superar miedos, confusión aclarada, verdad. Salir de la confusión, ver con claridad." },
  "19": { upright: "Éxito, vitalidad, alegría. Brillante con niño sobre caballo blanco. Logros, claridad, energía positiva radiante.", reversed: "Tristeza, fracaso temporal, falta de vitalidad. Período oscuro antes del amanecer." },
  "20": { upright: "Renacimiento, llamado, reflexión. Con el ángel Gabriel trompeteando. Segunda oportunidad, despertar espiritual.", reversed: "Autocrítica excesiva, negación, falta de reflexión. Ignorar las lecciones del pasado." },
  "21": { upright: "Completitud, logro, viaje. Con la bailarina en la guirnalda. Fin de un ciclo exitoso, integración, plenitud.", reversed: "Falta de cierre, incompletitud, estancamiento. No completar un proyecto importante." },

  // ═══════════════ COPAS ═══════════════
  "22": { upright: "Nuevas emociones, amor, compasión. Desbordando con cinco corrientes. Un nuevo comienzo emocional, derramamiento de sentimientos.", reversed: "Emociones reprimidas, vacío, negatividad. Cerrar el corazón, no expresar sentimientos." },
  "23": { upright: "Unión, armonía, amor mutuo. Dos personas intercambiando copas. Conexión profunda, atracción, equilibrio en relaciones.", reversed: "Desconexión, desequilibrio, ruptura. Conflicto en una relación importante." },
  "24": { upright: "Celebración, amistad, comunidad. Tres mujeres brindando. Alegría compartida, éxito grupal, creatividad.", reversed: "Soledad, excesos, traición. Falta de apoyo, celebración excesiva." },
  "25": { upright: "Apatía, contemplación, rechazo. Hombre bajo árbol con tres copas, cuarta ofrecida desde nube. Indiferencia, oportunidad ignorada.", reversed: "Acción, motivación, nuevos sentimientos. Salir del estancamiento emocional." },
  "26": { upright: "Pérdida, lamento, decepción. Figura en negro mirando copas derramadas. Duelo, arrepentimiento, pero quedan cosas.", reversed: "Aceptación, perdón, avanzar. Soltar el pasado, encontrar paz." },
  "27": { upright: "Nostalgia, inocencia, recuerdos. Niño mayor dando copa con flor a niño menor. Conexión con el pasado, bondad.", reversed: "Vivir en el pasado, inmadurez, idealización. Aferrarse a recuerdos." },
  "28": { upright: "Fantasía, elección, ilusión. Figura frente a copas en nubes. Opciones tentadoras, sueños, fantasías.", reversed: "Claridad, decisión, acción. Elegir un camino, ser realista." },
  "29": { upright: "Abandono, búsqueda, desilusión. Figura en rojo alejándose. Dejar atrás, buscar algo más profundo.", reversed: "Estancamiento, miedo al cambio, apego. No soltar lo que ya no funciona." },
  "30": { upright: "Satisfacción, logro, contentamiento. Hombre satisfecho con copas en arco. Deseos cumplidos, gratitud, bienestar.", reversed: "Insatisfacción, codicia, arrogancia. Nunca es suficiente, querer más." },
  "31": { upright: "Felicidad, armonía familiar, amor. Pareja abrazada, arcoíris con copas. Realización emocional, hogar, comunidad.", reversed: "Conflicto familiar, desilusión, separación. Problemas en el hogar." },
  "32": { upright: "Intuición, creatividad, mensaje emocional. Con pez en copa. Noticias inesperadas, inspiración.", reversed: "Inmadurez emocional, falta de creatividad, noticias malas." },
  "33": { upright: "Romanticismo, creatividad, embajador. Con armadura y copa dorada. Ofrecer corazón, arte, poesía.", reversed: "Celos, manipulación, fantasías irreales." },
  "34": { upright: "Compasión, intuición, serenidad. En el trono junto al mar. Mujer empática, sanadora, intuitiva.", reversed: "Dependencia emocional, inseguridad, negatividad." },
  "35": { upright: "Control emocional, diplomacia, sabiduría. En el trono en el mar. Hombre emocionalmente estable, negociador.", reversed: "Manipulación, agresión emocional, falta de control." },

  // ═══════════════ ESPADAS ═══════════════
  "36": { upright: "Claridad mental, verdad, breakthrough. Con corona y rama de olivo. Nueva idea, insight, justicia.", reversed: "Confusión, malentendidos, falta de claridad." },
  "37": { upright: "Indecisión, equilibrio, bloqueo. Con vendas, espadas cruzadas. Difícil elección, ceguera temporal.", reversed: "Decisión tomada, información revelada, claridad." },
  "38": { upright: "Dolor, traición, decepción. Atravesando corazón. Corazón roto, tristeza profunda, betrayl.", reversed: "Perdón, recuperación, superación. Sanar heridas, encontrar paz." },
  "39": { upright: "Descanso, recuperación, meditación. En tumba. Necesidad de pausa, restauración espiritual.", reversed: "Agitación, ansiedad, falta de descanso. Burnout, estrés." },
  "40": { upright: "Conflicto, derrota, ego. Con victorioso. Victoria a costa de otros, pérdida.", reversed: "Reconciliación, perdón, aprendizaje. Superar el conflicto." },
  "41": { upright: "Transición, viaje, recuperación. En barco. Dejar atrás dificultades, avanzar.", reversed: "Estancamiento, resistencia al cambio, bagaje emocional." },
  "42": { upright: "Estrategia, astucia, secretos. Robando. Engaño, acting alone, estrategia.", reversed: "Confesión, honestidad, arrepentimiento." },
  "43": { upright: "Restricción, encarcelamiento, impotencia. Con mujer vendada. Atado por circunstancias, victimismo.", reversed: "Liberación, claridad, empowerment. Romper cadenas, ver opciones." },
  "44": { upright: "Ansiedad, pesadillas, culpa. Con figura en cama. Insomnio, preocupación excesiva, miedo.", reversed: "Esperanza, recuperación, release. Los peores momentos pasan." },
  "45": { upright: "Fin, traición, rock bottom. Con figura caída. Final doloroso, pero nuevo amanecer.", reversed: "Recuperación, resistencia, segundo amanecer. Resistir el fin." },
  "46": { upright: "Curiosidad, vigilancia, nuevos ideas. Con espada. Observar, planificar, comunicar.", reversed: "Espionaje, críticas, falta de dirección." },
  "47": { upright: "Acción, determinación, velocidad. Cargando. Avanzar rápido, perseguir metas.", reversed: "Impulsividad, agresión, falta de tacto." },
  "48": { upright: "Independencia, claridad, honestidad. Con espada. Mujer directa, observadora, justa.", reversed: "Crueldad, fríaldad, manipulación." },
  "49": { upright: "Autoridad intelectual, justicia, liderazgo. En el trono. Hombre brillante, estratega.", reversed: "Tiranía, abuso de poder, frialdad." },

  // ═══════════════ BASTOS ═══════════════
  "50": { upright: "Inspiración, nuevo comienzo, potencial. Con brotes verdes. Chispa creativa, energía, pasión.", reversed: "Falta de dirección, retrasos, pérdida de interés." },
  "51": { upright: "Planificación, decisiones, mundo abierto. Mirando el mar. Mirar hacia el futuro, planificar.", reversed: "Miedo al cambio, estancamiento, falta de visión." },
  "52": { upright: "Expansión, exploración, visión. Con barcos. Ver oportunidades, anticipar el futuro.", reversed: "Frustración, retrasos, falta de preparación." },
  "53": { upright: "Celebración, hogar, armonía. Con guirnalda. Evento feliz, logro, estabilidad.", reversed: "Transición, inestabilidad, falta de celebración." },
  "54": { upright: "Conflicto, competencia, desacuerdo. Peleando. Desafío, rivalidad, crecimiento.", reversed: "Evitar conflicto, acuerdo, armonía." },
  "55": { upright: "Victoria, éxito, reconocimiento. Con victorioso. Ganador, confianza, logros públicos.", reversed: "Derrota, arrogancia, falta de reconocimiento." },
  "56": { upright: "Defensa, perseverancia, desafío. Defendiendo posición. Mantener posiciones, luchar.", reversed: "Rendirse, agotamiento, derrota." },
  "57": { upright: "Velocidad, movimiento, acción. Volando. Rapidez, viajes, noticias llegando.", reversed: "Retrasos, estancamiento, frustración." },
  "58": { upright: "Resiliencia, persistencia, defensa. Cansado. Aguantar, fortaleza, resistencia.", reversed: "Agotamiento, paranoia, desconfianza." },
  "59": { upright: "Carga, responsabilidad, estrés. Cargando. Sobrecarga, deber, agotamiento.", reversed: "Liberación, delegación, alivio. Soltar cargas innecesarias." },
  "60": { upright: "Entusiasmo, exploración, aventura. Mirando bastón. Energía joven, curiosidad.", reversed: "Falta de dirección, inmadurez, retrasos." },
  "61": { upright: "Pasión, energía, aventura. Cargando. Acción audaz, entusiasmo, viaje.", reversed: "Impulsividad, arrogancia, energía desperdiciada." },
  "62": { upright: "Confianza, calidez, determinación. Con gato negro. Mujer segura, carismática.", reversed: "Celos, egoísmo, inseguridad." },
  "63": { upright: "Liderazgo natural, visión, emprendimiento. En el trono. Hombre inspirador, líder nato.", reversed: "Tiranía, impulsividad, falta de visión." },

  // ═══════════════ OROS ═══════════════
  "64": { upright: "Nueva oportunidad, prosperidad, estabilidad. Con jardín. Inicio de proyecto exitoso, abundancia.", reversed: "Oportunidad perdida, falta de planificación, pobreza." },
  "65": { upright: "Equilibrio, adaptabilidad, gestión. Bailando. Equilibrar prioridades, flexibilidad.", reversed: "Desequilibrio, sobrecarga, mala gestión." },
  "66": { upright: "Trabajo en equipo, maestría, colaboración. Trabajando. Éxito grupal, habilidad técnica.", reversed: "Falta de trabajo, mediocridad, desacuerdo." },
  "67": { upright: "Control, seguridad, ahorro. Aferrando. Proteger recursos, estabilidad financiera.", reversed: "Avaricia, miedo a perder, generosidad excesiva." },
  "68": { upright: "Pobreza, necesidad, aislamiento. Afuera de iglesia. Dificultad financiera, exclusión.", reversed: "Recuperación, ayuda, esperanza. Superar dificultades, recibir apoyo." },
  "69": { upright: "Generosidad, caridad, equilibrio. Dando monedas. Dar y recibir, justicia social.", reversed: "Deudas, dependencia, generosidad falsa." },
  "70": { upright: "Paciencia, inversión, espera. Cultivando. Evaluar progreso, recompensa futura.", reversed: "Falta de paciencia, resultado insatisfactorio, malgasto." },
  "71": { upright: "Dedicación, maestría, trabajo. Tallando. Aprendizaje, habilidad, perfeccionamiento.", reversed: "Mediocridad, falta de dedicación, aburrimiento." },
  "72": { upright: "Independencia, lujo, logro. En jardín. Autosuficiencia, elegancia, éxito financiero.", reversed: "Dependencia, excesos, superficialidad." },
  "73": { upright: "Legado, familia, estabilidad. Con familia. Riqueza generacional, tradición, hogar.", reversed: "Pérdida financiera, problemas familiares, inestabilidad." },
  "74": { upright: "Estudio, ambición, oportunidad. Mirando moneda. Nuevos proyectos, aprendizaje práctico.", reversed: "Falta de progreso, pereza, oportunidad perdida." },
  "75": { upright: "Diligencia, rutina, perseverancia. En caballo pesado. Trabajo constante, confiabilidad.", reversed: "Pereza, estancamiento, falta de progreso." },
  "76": { upright: "Abundancia, nutrición, práctica. En jardín. Mujer práctica, generosa, tierra.", reversed: "Dependencia material, descuido, negatividad." },
  "77": { upright: "Éxito financiero, liderazgo práctico, abundancia. En jardín. Hombre próspero, generoso.", reversed: "Avaricia, materialismo, corrupción." }
};
